### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by karamjaber** [magnuswatn/certsrv#1]
I have noticed that you are using CertificateSigningRequestBuilder.
How can i add a public key for the certificate signing request builder object ?

**Comment by magnuswatn** [comment]
Hi,

You can't add a public key to the CertificateSigningRequestBuilder, but you don't need to. The sign method will set the public key in the request to the one associated with the private key used to sign the request. So just call the sign method with the private key, and the csr object will have the correct public key.

**Comment by magnuswatn** [comment]
Really not an issue.
