### ISSUE TITLE
Improvement Request: Enable use of personal certificates

### ISSUE THREAD

**Issue by sirferl** [magnuswatn/certsrv#11]
Hello,
I used certsrv to develop a Lemur-Issuer Plugin ([Lemur](https://github.com/Netflix/lemur).
For authorization, we use personal certificates.
I succeeded to connect with our AD by "patching" the local .py file like this:
 _def _set_credentials(self, username, password):
        if self.auth_method == "ntlm":
            from requests_ntlm import HttpNtlmAuth

            self.session.auth = HttpNtlmAuth(username, password)
        else:
             # self.session.auth = (username, password)
             self.session.cert='/home/lemur/.lemur/client.cert'_

To cleanly improve this new parameters like "cert" nad "cert_path" are needed and a third path in the if :
 def _set_credentials(self, username, password):
        if self.auth_method == "ntlm":
            from requests_ntlm import HttpNtlmAuth

            self.session.auth = HttpNtlmAuth(username, password)
       elif  self.auth_method == "cert":
            self.session.cert=certpath
       else:
            self.session.auth = (username, password)
             
I would be very happy, if you could integrate this feature in the release.
I have no experience with adding features to github projects but if you could give me directions, I could enter the changes myself. 

Thank you
regards
ferdinand

**Comment by magnuswatn** [comment]
This should be no problem. I'll fix.

**Comment by sirferl** [comment]
Great, thank you
ferl

**Comment by magnuswatn** [comment]
Hi,

Can you take a look at the latest commit in the develop branch, and see if it works for you? Use the username parameter to point to a certificate, and the password parameter to point to a private key, like this:
```
ca_server = Certsrv("my-adcs-server.example.net", "/path/to/cert", "/path/to/key", auth_method="cert")
pem_cert = ca_server.get_cert(pem_req, "WebServer")
```

Magnus

**Comment by sirferl** [comment]
Works like a charm 
Thank you.
regards
sirferl

**Comment by magnuswatn** [comment]
Version 2.1.0 released, with support for client certificates.
