### ISSUE TITLE
Stupid error with Certsrv

### ISSUE THREAD

**Issue by RFC1920** [magnuswatn/certsrv#16]
On Centos6 running either python 2.75 or 3.6.8, I get the following error.
ImportError: cannot import name Certsrv

If I change the line to "from certsrv import *" I get:

NameError: name 'Certsrv' is not defined

I am going by the example at https://certsrv.readthedocs.io/en/latest/certsrv.html.

**Comment by magnuswatn** [comment]
That does indeed sound like a stupid error.

How did you install certsrv? What version do you have (`import certsrv` then `certsrv.__version__`)?

**Comment by RFC1920** [comment]
I guess it helps not to call your test file certsrv.py.  I renamed it.  On to another fun error:

ImportError: bad magic number in 'certsrv': b'\x03\xf3\r\n'

**Comment by RFC1920** [comment]
Never mind, got it sorted I think.  Deleted the pyc files and am on to a hopefully simple fix for untrusted cert.  Thanks!

**Comment by RFC1920** [comment]
Was my fault for duplicating the module name as my script.  Still having issues but not your fault.
