### ISSUE TITLE
Unable to login to ADCS

### ISSUE THREAD

**Issue by Akasurde** [magnuswatn/certsrv#2]
I am unable to login into ADCS server using 

```
get_cert('adcs.example.test', pem_req, server, username, password)
```
I always get 401, Am I missing something here ?

**Comment by MartinTerp** [comment]
Maybe you occured on the same issue that i just did.
Our certsrv uses kerberos and not "basic", and this lib dosnt support this

**Comment by Akasurde** [comment]
@MartinTerp I even tried to enable Basic authentication in IIS, but nothing worked.

**Comment by magnuswatn** [comment]
That's weird. Are you able to login using a browser with the same username and password?

**Comment by Akasurde** [comment]
@magnuswatn Yes, I am able to login to ADCS using different browsers and different machines. Thats the weird part. I also installed and enabled "Basic Authentication" in ADCS.

**Comment by MartinTerp** [comment]
Im going to make a pull request with the support for NTLM so you can test out the kerberos part out, to see if that works better.

**Comment by magnuswatn** [comment]
@Akasurde Browser often support NTLM as well. Check if the server sends the header "WWW-Authenticate:Basic realm="test"" on the 401 response.

@MartinTerp Nice!

**Comment by theballdredge** [comment]
I found it necessary to specify the domain (ei user@domain.tld) to get the script to function.  Oddly, only for some accounts.  It is not clear yet what differentiates an account that requires the domain from one that does not.

**Comment by magnuswatn** [comment]
Version 1.6.1 with NTLM support is now released. Feel free to test and see if that solves your problem @Akasurde.

**Comment by Akasurde** [comment]
@magnuswatn Thanks. I will check and report here once done.

**Comment by jetersen** [comment]
@magnuswatn I can report back that it is working 😄 We are actively using NTLM support 🙌
