### ISSUE TITLE
Cannot specify root CA

### ISSUE THREAD

**Issue by theballdredge** [magnuswatn/certsrv#3]
on nonwindows systems, the library fails to submit requests to a private CA:

`urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>`

tried exporting SSL_CERT_FILE, but that appears to only work for requests, not urllib2.

would it be possible to add an optional parameter to specify the CA root?

**Comment by magnuswatn** [comment]
It works on RHEL/Fedora if you add the cert to the CAs trusted by the system (copy it to /etc/pki/ca-trust/source/anchors/ and "update-ca-trust"). But sure, this should be no problem - I will have a look in a couple of days.

**Comment by magnuswatn** [comment]
Sorry this took so long. Can you test the version in the [cafile-parameter branch](https://github.com/magnuswatn/certsrv/tree/cafile-parameter) and see if it solves your problem? Thanks.

**Comment by theballdredge** [comment]
looks good save one change i submitted #4 for.  working for me otherwise, thanks for the quick response.

**Comment by magnuswatn** [comment]
Ah, I missed that one - thanks! I wrote some new test cases that catches my error, and merged your change in. If everything looks good to you, I can merge to master and release a new version to PyPi.

**Comment by theballdredge** [comment]
sure thing.  looks right to me.

**Comment by magnuswatn** [comment]
Sorry this took so long, but version 1.6.1 is now released with support for the cafile parameter.
Be aware that it is now a named argument, not a positional argument.
