### ISSUE TITLE
um, how to run that thing?

### ISSUE THREAD

**Issue by ghost** [magnuswatn/certsrv#7]
hi there,

it might be a stupid question, but how do i run that script to make means work?

i am not a dev.

**Comment by magnuswatn** [comment]
Hi,

Sorry for the late reply. This isn't a script that you can run on it's own - it's a library you can use in your own scripts. Check out the [documentation](https://certsrv.readthedocs.io/en/latest/examples.html) for examples on how to use it.

**Comment by ghost** [comment]
thank you for your reply.
anyway
it will take years until i am capable of using this library :)

or can i take f.e. the first example, save it in a py file and run it somehow afterwards? (adjusting the cert server adress of course...)

**Comment by magnuswatn** [comment]
Yes, you could do that :-) If you can describe your needs, I may be able to make a quick script for you as well.

**Comment by magnuswatn** [comment]
No response, so just closing this.
